"""Initial migration

Revision ID: fd1f29911cb5
Revises:
Create Date: 2026-09-11 12:13:57.751628

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "fd1f29911cb5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
